name: Sync to Hugging Face Spaces
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://lucacarlino04:$HF_TOKEN@huggingface.co/spaces/lucacarlino04/redAntisocial
          git push --force space main
